# The URL the site will be built for
base_url = "https://tulpje.github.io"
title = "Tulpje"
description = "A Multi-Purpose Discord Bot"
default_language = "en"
theme = "zola-hook"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"
